export type MaterialCategory = "wood" | "gem" | "spacer";

export type ChakraType =
  | "root" // 海底轮
  | "sacral" // 生殖轮/脐轮
  | "solar" // 太阳神经丛/胃轮
  | "heart" // 心轮
  | "throat" // 喉轮
  | "thirdEye" // 三眼轮/眉心轮
  | "crown"; // 顶轮

export type ElementType = "wood" | "fire" | "earth" | "metal" | "water";

export interface BeadMaterial {
  id: string;
  name: string;
  nameZh: string;
  category: MaterialCategory;
  description: string;
  descriptionZh: string;
  origin: string; // 产地背书 (e.g., Dacheng Master Studio / Dacheng Rosewood Hub)
  colors: {
    base: string; // Base color
    highlight: string; // Specular shine
    shadow: string; // Shadow tone
    patina1y: string; // 1-year patina tone
    patina5y: string; // 5-year deep patina tone
    patina10y: string; // 10-year jade-like tone
    pattern?: "wood-grain" | "gold-fiber" | "speckled" | "swirl" | "metallic";
  };
  chakras: ChakraType[];
  element: ElementType;
  zodiacs: string[]; // e.g. ["Taurus", "Virgo", "Capricorn"]
  aromaScore: number; // 1 to 5
  aromaNote?: string;
  aromaNoteZh?: string;
  basePrice: number; // Base price for 8mm bead in USD ($)
}

export const BEAD_SIZES = [
  { mm: 6, label: "6mm (Delicate)", multiplier: 0.8 },
  { mm: 8, label: "8mm (Classic Standard)", multiplier: 1.0 },
  { mm: 10, label: "10mm (Most Popular)", multiplier: 1.3 },
  { mm: 12, label: "12mm (Bold & Substantial)", multiplier: 1.7 },
  { mm: 15, label: "15mm (Statement / Meditation)", multiplier: 2.3 },
  { mm: 18, label: "18mm (Collector's Heavy)", multiplier: 3.2 },
];

export const SACRED_WOODS: BeadMaterial[] = [
  {
    id: "green-sandalwood",
    name: "Green Sandalwood (Verawood)",
    nameZh: "天然野生老料绿檀",
    category: "wood",
    description: "Known as the Holy Wood. Naturally fragrant, develops an enchanting jade-green patina with sunlight and wear.",
    descriptionZh: "被誉为圣木。自带天然清幽檀香，随日照与佩戴逐渐蜕变为碧玉般的青翠包浆，安神定气。",
    origin: "Dacheng Certified Wild Stock",
    colors: {
      base: "#5f6f52",
      highlight: "#a9b388",
      shadow: "#283618",
      patina1y: "#4a5d3f",
      patina5y: "#314426",
      patina10y: "#1f2e18",
      pattern: "wood-grain",
    },
    chakras: ["heart", "root"],
    element: "wood",
    zodiacs: ["Taurus", "Virgo", "Libra"],
    aromaScore: 5,
    aromaNote: "Sweet, earthy herbal sandalwood aroma",
    aromaNoteZh: "天然清幽甜润檀香",
    basePrice: 3.5,
  },
  {
    id: "gold-phoebe",
    name: "Gold Phoebe (Jin Si Nan)",
    nameZh: "四川百年老料金丝楠",
    category: "wood",
    description: "Imperial Palace wood reserved for royalty. Radiates shimmering golden threads under sunlight with delicate orchid fragrance.",
    descriptionZh: "明清皇室御用帝王木。在阳光下折射流动的天然金丝水波纹，散发幽雅淡竹幽兰香气。",
    origin: "Ancient Root Stock Extraction",
    colors: {
      base: "#b4843b",
      highlight: "#fde047",
      shadow: "#784b16",
      patina1y: "#9a6c28",
      patina5y: "#7c531a",
      patina10y: "#5a3a0e",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "crown"],
    element: "earth",
    zodiacs: ["Leo", "Sagittarius", "Aries"],
    aromaScore: 4,
    aromaNote: "Gentle imperial orchid aroma",
    aromaNoteZh: "幽雅天然兰花清香",
    basePrice: 5.5,
  },
  {
    id: "ebony-wood",
    name: "Black Ebony (Dense Sinking Wood)",
    nameZh: "高密沉水黑檀老料",
    category: "wood",
    description: "Dense, sinking dark wood that polishes to a piano-lacquer mirror finish. Ultimate grounding and shield against negative energy.",
    descriptionZh: "密度极高秒沉水，抛光后呈现如钢琴烤漆般的深邃镜面光泽。提供强大的定力与避煞护佑。",
    origin: "Dacheng Premium Selection",
    colors: {
      base: "#1c1917",
      highlight: "#57534e",
      shadow: "#09090b",
      patina1y: "#18181b",
      patina5y: "#0f0f11",
      patina10y: "#050506",
      pattern: "wood-grain",
    },
    chakras: ["root"],
    element: "water",
    zodiacs: ["Scorpio", "Capricorn", "Aquarius"],
    aromaScore: 2,
    aromaNote: "Subtle woody grounding scent",
    aromaNoteZh: "内敛沉静木质香",
    basePrice: 3.0,
  },
  {
    id: "thuja-cypress",
    name: "Cliff Cypress (Taihang Ya Bai)",
    nameZh: "太行崖柏陈化舍利料",
    category: "wood",
    description: "Surviving on steep cliffs for centuries. Rich in natural essential oils with swirling bird-eye flames and soothing herbal fragrance.",
    descriptionZh: "长于悬崖峭壁百年陈化。富含天然挥发油，雀眼虎皮纹理绚丽，散发浓郁中草药安神香气。",
    origin: "Taihang Mountain Cliff Harvest",
    colors: {
      base: "#c27838",
      highlight: "#fed7aa",
      shadow: "#7c2d12",
      patina1y: "#a85d22",
      patina5y: "#8c4413",
      patina10y: "#652c08",
      pattern: "swirl",
    },
    chakras: ["sacral", "solar"],
    element: "fire",
    zodiacs: ["Aries", "Gemini", "Leo"],
    aromaScore: 5,
    aromaNote: "Rich cedar & sweet herbal medicine notes",
    aromaNoteZh: "浓郁柏香与中药甜香",
    basePrice: 4.5,
  },
  {
    id: "peach-wood",
    name: "Sacred Peach Wood (Tao Mu)",
    nameZh: "泰山雷击桃木护身料",
    category: "wood",
    description: "The premier protective wood in Eastern culture. Renowned for warding off negativity and preserving inner vitality.",
    descriptionZh: "东方道家首席护身圣木。自古用于避险纳福、固本培元，色泽温和细腻。",
    origin: "Mount Tai Heritage Grove",
    colors: {
      base: "#d97706",
      highlight: "#fde68a",
      shadow: "#92400e",
      patina1y: "#b45309",
      patina5y: "#9a3412",
      patina10y: "#7c2d12",
      pattern: "wood-grain",
    },
    chakras: ["solar", "heart"],
    element: "wood",
    zodiacs: ["Cancer", "Pisces", "Virgo"],
    aromaScore: 2,
    aromaNote: "Mild warm fruitwood nuance",
    aromaNoteZh: "温润淡雅果木气息",
    basePrice: 2.8,
  },
  {
    id: "rosewood",
    name: "Red Rosewood (Suanzhi)",
    nameZh: "大红酸枝老料 (红木正统)",
    category: "wood",
    description: "Classic Chinese imperial timber. Features deep crimson ribbons, oily high-density grain, and timeless stately elegance.",
    descriptionZh: "明清家具正统红木。深红褐沉水黑筋纹理，油脂饱满，岁月沉淀后红润如琥珀。",
    origin: "Dacheng Heritage Kiln Stock",
    colors: {
      base: "#831843",
      highlight: "#f472b6",
      shadow: "#500724",
      patina1y: "#701a38",
      patina5y: "#540f28",
      patina10y: "#3b071a",
      pattern: "wood-grain",
    },
    chakras: ["root", "sacral"],
    element: "fire",
    zodiacs: ["Scorpio", "Capricorn", "Taurus"],
    aromaScore: 3,
    aromaNote: "Tart, regal antique wooden scent",
    aromaNoteZh: "古典端庄醇厚酸香",
    basePrice: 4.0,
  },
];

export const HEALING_CRYSTALS: BeadMaterial[] = [
  {
    id: "natural-turquoise",
    name: "Natural Turquoise (Lv Song Shi)",
    nameZh: "天然原矿高瓷绿松石",
    category: "gem",
    description: "The stone of the Throat Chakra. Inspires truthful expression, clear communication, and emotional serenity.",
    descriptionZh: "原矿高瓷无优化，青天一抹碧玉色。对应喉轮，增强沟通表达与心灵澄净。",
    origin: "Hubei Zhushan Certified Mine",
    colors: {
      base: "#06b6d4",
      highlight: "#a5f3fc",
      shadow: "#0e7490",
      patina1y: "#0891b2",
      patina5y: "#0e7490",
      patina10y: "#155e75",
      pattern: "speckled",
    },
    chakras: ["throat", "heart"],
    element: "water",
    zodiacs: ["Sagittarius", "Pisces", "Aquarius"],
    aromaScore: 1,
    basePrice: 6.0,
  },
  {
    id: "lapis-lazuli",
    name: "Royal Lapis Lazuli (Qing Jin Shi)",
    nameZh: "阿富汗帝王青金石 (带金星)",
    category: "gem",
    description: "Deep celestial blue with sparkling golden pyrite specks. Awakens the Third Eye for intuition, wisdom, and mental clarity.",
    descriptionZh: "深邃帝王群青点缀天然金色黄铁矿。对应三眼轮与眉心轮，开启灵性智慧与直觉洞察。",
    origin: "Badakhshan Ancient Mine",
    colors: {
      base: "#1d4ed8",
      highlight: "#93c5fd",
      shadow: "#1e3a8a",
      patina1y: "#1e40af",
      patina5y: "#1e3a8a",
      patina10y: "#172554",
      pattern: "speckled",
    },
    chakras: ["thirdEye", "throat"],
    element: "water",
    zodiacs: ["Libra", "Sagittarius", "Virgo"],
    aromaScore: 1,
    basePrice: 5.0,
  },
  {
    id: "red-agate",
    name: "Red Agate (Nan Hong Ma Nao)",
    nameZh: "天然保山南红玛瑙",
    category: "gem",
    description: "Vibrant crimson stone of vitality and courage. Activates the Root Chakra to restore physical passion and emotional balance.",
    descriptionZh: "柿子红天然胶质感。对应海底轮，激发充沛生命力、勇气与内在温暖。",
    origin: "Yunnan Baoshan Heritage Mine",
    colors: {
      base: "#dc2626",
      highlight: "#fca5a5",
      shadow: "#7f1d1d",
      patina1y: "#b91c1c",
      patina5y: "#991b1b",
      patina10y: "#7f1d1d",
      pattern: "swirl",
    },
    chakras: ["root", "sacral"],
    element: "fire",
    zodiacs: ["Aries", "Scorpio", "Leo"],
    aromaScore: 1,
    basePrice: 5.5,
  },
  {
    id: "tigers-eye",
    name: "Golden Tiger's Eye (Hu Yan Shi)",
    nameZh: "天然金虎眼石 (猫眼闪光)",
    category: "gem",
    description: "Silky chatoyancy with dynamic golden-brown light rays. Amplifies confidence, wealth magnetism, and willpower.",
    descriptionZh: "天然流动丝绢猫眼光彩。对应太阳轮，汇聚财富磁场、决断力与无畏自信。",
    origin: "Southern Africa Select Gem",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#713f12",
      patina1y: "#a16207",
      patina5y: "#854d0e",
      patina10y: "#713f12",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "root"],
    element: "earth",
    zodiacs: ["Leo", "Capricorn", "Gemini"],
    aromaScore: 1,
    basePrice: 4.0,
  },
  {
    id: "black-obsidian",
    name: "Rainbow Obsidian (Hei Yao Shi)",
    nameZh: "墨西哥彩虹眼黑曜石",
    category: "gem",
    description: "Volcanic glass with subtle iridescent rings. Powerful psychic protection stone that absorbs negative emotional energies.",
    descriptionZh: "火山熔岩天然凝结，逆光泛出神秘彩虹环。最强辟邪排浊与负能量吸收石。",
    origin: "Mexican Volcanic Highlands",
    colors: {
      base: "#18181b",
      highlight: "#52525b",
      shadow: "#09090b",
      patina1y: "#18181b",
      patina5y: "#09090b",
      patina10y: "#000000",
      pattern: "swirl",
    },
    chakras: ["root"],
    element: "water",
    zodiacs: ["Scorpio", "Sagittarius", "Capricorn"],
    aromaScore: 1,
    basePrice: 3.5,
  },
  {
    id: "amethyst",
    name: "Deep Purple Amethyst (Zi Shui Jing)",
    nameZh: "乌拉圭深紫水晶",
    category: "gem",
    description: "Translucent royal purple crystal of spiritual serenity. Calms overactive minds and facilitates restful deep sleep.",
    descriptionZh: "晶莹剔透高贵紫罗兰色。对应顶轮，抚平焦虑思绪，助益深度冥想与甜美睡眠。",
    origin: "Uruguay Deep Vault",
    colors: {
      base: "#7c3aed",
      highlight: "#ddd6fe",
      shadow: "#4c1d95",
      patina1y: "#6d28d9",
      patina5y: "#5b21b6",
      patina10y: "#4c1d95",
      pattern: "swirl",
    },
    chakras: ["crown", "thirdEye"],
    element: "metal",
    zodiacs: ["Aquarius", "Pisces", "Virgo"],
    aromaScore: 1,
    basePrice: 4.8,
  },
  {
    id: "hetian-jade",
    name: "Hetian Nephrite Jade (He Tian Yu)",
    nameZh: "新疆和田羊脂白玉 / 青玉",
    category: "gem",
    description: "The quintessential stone of Eastern virtue. Oily, tactile smoothness that nurtures gentleness, longevity, and purity.",
    descriptionZh: "东方温润君子之玉。细腻如凝脂，滋养平和心性与长寿安康之福。",
    origin: "Xinjiang Kunlun Mountain River",
    colors: {
      base: "#e2e8f0",
      highlight: "#ffffff",
      shadow: "#94a3b8",
      patina1y: "#cbd5e1",
      patina5y: "#94a3b8",
      patina10y: "#64748b",
      pattern: "swirl",
    },
    chakras: ["heart", "crown"],
    element: "metal",
    zodiacs: ["Taurus", "Cancer", "Libra"],
    aromaScore: 1,
    basePrice: 7.5,
  },
];

export const SACRED_SPACERS: BeadMaterial[] = [
  {
    id: "silver-lotus",
    name: "925 Silver Lotus Guru (Lian Hua Fo Tou)",
    nameZh: "925 纯银浮雕莲花佛头三通",
    category: "spacer",
    description: "Handcrafted 925 sterling silver centerpiece symbolizing purity, rebirth, and spiritual awakening.",
    descriptionZh: "手工錾刻 925 纯银莲花三通母珠，象征出淤泥而不染的心灵解脱与觉悟。",
    origin: "Master Silver Smith Guild",
    colors: {
      base: "#e2e8f0",
      highlight: "#ffffff",
      shadow: "#64748b",
      patina1y: "#cbd5e1",
      patina5y: "#94a3b8",
      patina10y: "#475569",
      pattern: "metallic",
    },
    chakras: ["crown", "heart"],
    element: "metal",
    zodiacs: ["Pisces", "Cancer", "Libra"],
    aromaScore: 1,
    basePrice: 12.0,
  },
  {
    id: "pixiu-charm",
    name: "Silver Pixiu Wealth Guardian (Pi Xiu)",
    nameZh: "925 纯银招财纳福小貔貅",
    category: "spacer",
    description: "Mythical Eastern beast renowned for attracting wealth, safeguarding fortune, and dispelling misfortune.",
    descriptionZh: "吞吐四方之财的神兽护佑，驱除霉运、守护财富磁场稳固不散。",
    origin: "Heritage Foundry Craft",
    colors: {
      base: "#cbd5e1",
      highlight: "#ffffff",
      shadow: "#475569",
      patina1y: "#94a3b8",
      patina5y: "#64748b",
      patina10y: "#334155",
      pattern: "metallic",
    },
    chakras: ["solar", "root"],
    element: "metal",
    zodiacs: ["Leo", "Taurus", "Scorpio"],
    aromaScore: 1,
    basePrice: 14.0,
  },
  {
    id: "om-mantra",
    name: "Tibetan Om Six-Word Spacer (Om Mantra)",
    nameZh: "藏银六字真言转经隔珠",
    category: "spacer",
    description: "Embossed with the sacred Sanskrit syllable Om Mani Padme Hum for constant inner protection and spiritual harmony.",
    descriptionZh: "微雕六字大明咒梵文，每转动一次即是一次持咒祈福，清净身口意。",
    origin: "Tibetan Artisan Collective",
    colors: {
      base: "#94a3b8",
      highlight: "#f1f5f9",
      shadow: "#334155",
      patina1y: "#64748b",
      patina5y: "#475569",
      patina10y: "#1e293b",
      pattern: "metallic",
    },
    chakras: ["throat", "thirdEye"],
    element: "metal",
    zodiacs: ["Sagittarius", "Aquarius", "Gemini"],
    aromaScore: 1,
    basePrice: 8.0,
  },
  {
    id: "brass-ring",
    name: "Vintage Brass Spacer Ring (Huang Tong Ge Pian)",
    nameZh: "复古手工打磨黄铜隔片",
    category: "spacer",
    description: "Slim antique brass ring used between beads to protect timber, improve flex, and add warm vintage character.",
    descriptionZh: "手工复古做旧黄铜薄片，保护木质不磨损，增加手串流线韵律感。",
    origin: "Dacheng Handcraft Lab",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#854d0e",
      patina1y: "#a16207",
      patina5y: "#713f12",
      patina10y: "#422006",
      pattern: "metallic",
    },
    chakras: ["solar"],
    element: "metal",
    zodiacs: ["Gemini", "Virgo", "Capricorn"],
    aromaScore: 1,
    basePrice: 1.5,
  },
];

export const ALL_MATERIALS: BeadMaterial[] = [
  ...SACRED_WOODS,
  ...HEALING_CRYSTALS,
  ...SACRED_SPACERS,
];

export function getMaterialById(id: string): BeadMaterial | undefined {
  return ALL_MATERIALS.find((m) => m.id === id);
}
