export type MaterialCategory = "wood" | "gem" | "spacer";

export type ChakraType =
  | "root" // 海底轮
  | "sacral" // 生殖轮/脐轮
  | "solar" // 太阳神经丛/胃轮
  | "heart" // 心轮
  | "throat" // 喉轮
  | "thirdEye" // 三眼轮/眉心轮
  | "crown"; // 顶轮

export type ElementType = "wood" | "fire" | "earth" | "metal" | "water";

export interface BeadMaterial {
  id: string;
  name: string;
  nameZh: string;
  category: MaterialCategory;
  description: string;
  descriptionZh: string;
  origin: string;
  image: string; // Real HD visual asset path
  colors: {
    base: string;
    highlight: string;
    shadow: string;
    patina1y: string;
    patina5y: string;
    patina10y: string;
    pattern?: "wood-grain" | "gold-fiber" | "speckled" | "swirl" | "metallic";
  };
  chakras: ChakraType[];
  element: ElementType;
  zodiacs: string[];
  aromaScore: number;
  aromaNote?: string;
  aromaNoteZh?: string;
  basePrice: number;
}

export const BEAD_SIZES = [
  { mm: 6, label: "6mm (Delicate)", multiplier: 0.8 },
  { mm: 8, label: "8mm (Classic Standard)", multiplier: 1.0 },
  { mm: 10, label: "10mm (Most Popular)", multiplier: 1.3 },
  { mm: 12, label: "12mm (Bold & Substantial)", multiplier: 1.7 },
  { mm: 15, label: "15mm (Statement / Meditation)", multiplier: 2.3 },
  { mm: 18, label: "18mm (Collector's Heavy)", multiplier: 3.2 },
];

/**
 * 100% CITES-Compliant & Global Customs-Safe Sacred Woods
 * (Removed restricted Dalbergia / Rosewood & Pterocarpus to guarantee zero customs seizure risk)
 */
export const SACRED_WOODS: BeadMaterial[] = [
  {
    id: "green-sandalwood",
    name: "Green Sandalwood (Verawood)",
    nameZh: "天然野生老料绿檀",
    category: "wood",
    description: "Known as the Holy Wood. Naturally fragrant, develops an enchanting jade-green patina with sunlight and wear.",
    descriptionZh: "被誉为圣木。自带天然清幽檀香，随日照与佩戴逐渐蜕变为碧玉般的青翠包浆，安神定气。",
    origin: "Dacheng Certified Wild Stock",
    image: "/beads/green-sandalwood.png",
    colors: {
      base: "#5f6f52",
      highlight: "#a9b388",
      shadow: "#283618",
      patina1y: "#4a5d3f",
      patina5y: "#314426",
      patina10y: "#1f2e18",
      pattern: "wood-grain",
    },
    chakras: ["heart", "root"],
    element: "wood",
    zodiacs: ["Taurus", "Virgo", "Libra"],
    aromaScore: 5,
    aromaNote: "Sweet, earthy herbal sandalwood aroma",
    aromaNoteZh: "天然清幽甜润檀香",
    basePrice: 3.5,
  },
  {
    id: "gold-phoebe",
    name: "Gold Phoebe (Jin Si Nan)",
    nameZh: "四川百年老料金丝楠",
    category: "wood",
    description: "Imperial Emperor's timber. Shimmers with liquid golden ribbons under light, radiating an ethereal bamboo-orchid perfume.",
    descriptionZh: "明清皇室御用帝王木。在阳光下折射流动天然金丝水波纹，散发幽雅淡竹幽兰果香，温润无比。",
    origin: "Ancient Root Stock Sichuan",
    image: "/beads/gold-phoebe.png",
    colors: {
      base: "#b4843b",
      highlight: "#e9c46a",
      shadow: "#704812",
      patina1y: "#9a6c25",
      patina5y: "#7c5316",
      patina10y: "#5c3c0d",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "crown"],
    element: "wood",
    zodiacs: ["Leo", "Sagittarius", "Aries"],
    aromaScore: 4,
    aromaNote: "Delicate orchid-fruity fragrance",
    aromaNoteZh: "幽雅竹兰清甜果香",
    basePrice: 5.5,
  },
  {
    id: "ebony-wood",
    name: "Sinking Black Ebony (Hei Tan)",
    nameZh: "高密沉水黑檀老料",
    category: "wood",
    description: "High-density sinking timber. Polishes to a piano-black obsidian sheen, grounding intense spiritual focus and shielding energy.",
    descriptionZh: "密度极高秒沉水，抛光后呈现如钢琴烤漆般的深邃镜面光泽。提供强大的定力与避煞气场。",
    origin: "Dacheng Premium Selection",
    image: "/beads/ebony-wood.png",
    colors: {
      base: "#1c1917",
      highlight: "#44403c",
      shadow: "#0c0a09",
      patina1y: "#18181b",
      patina5y: "#09090b",
      patina10y: "#000000",
      pattern: "wood-grain",
    },
    chakras: ["root"],
    element: "water",
    zodiacs: ["Capricorn", "Scorpio", "Aquarius"],
    aromaScore: 2,
    aromaNote: "Subtle dry wood essence",
    aromaNoteZh: "沉稳干木暗香",
    basePrice: 3.0,
  },
  {
    id: "thuja-cypress",
    name: "Taihang Mountain Cliff Thuja (Ya Bai)",
    nameZh: "太行崖柏陈化舍利料",
    category: "wood",
    description: "Centuries-aged cliff bonsai cypress. Packed with aromatic oils, displaying dense tiger-skin burl eyes with rich cedar notes.",
    descriptionZh: "长于悬崖峭壁百年陈化。富含天然挥发油，雀眼虎皮纹理绚丽，散发浓郁中草药蜜香。",
    origin: "Taihang Mountain Cliff Burl",
    image: "/beads/thuja-cypress.png",
    colors: {
      base: "#8c3b24",
      highlight: "#d97736",
      shadow: "#4a190f",
      patina1y: "#742c19",
      patina5y: "#5a1f11",
      patina10y: "#3f1309",
      pattern: "wood-grain",
    },
    chakras: ["thirdEye", "solar"],
    element: "wood",
    zodiacs: ["Gemini", "Aquarius", "Aries"],
    aromaScore: 5,
    aromaNote: "Rich cedar & sweet herbal medicine notes",
    aromaNoteZh: "浓郁柏香与中药甜香",
    basePrice: 4.5,
  },
  {
    id: "peach-wood",
    name: "Sacred Peach Wood (Tao Mu)",
    nameZh: "泰山雷击桃木护身料",
    category: "wood",
    description: "The premier protective wood in Eastern culture. Renowned for warding off negativity and preserving inner vitality.",
    descriptionZh: "东方道家首席护身圣木。自古用于避险纳福、固本培元，色泽温和细腻。",
    origin: "Mount Tai Heritage Grove",
    image: "/beads/peach-wood.png",
    colors: {
      base: "#d97706",
      highlight: "#fde68a",
      shadow: "#92400e",
      patina1y: "#b45309",
      patina5y: "#9a3412",
      patina10y: "#7c2d12",
      pattern: "wood-grain",
    },
    chakras: ["solar", "heart"],
    element: "wood",
    zodiacs: ["Cancer", "Pisces", "Virgo"],
    aromaScore: 2,
    aromaNote: "Mild warm fruitwood nuance",
    aromaNoteZh: "温润淡雅果木气息",
    basePrice: 2.8,
  },
  {
    id: "indian-sandalwood",
    name: "Indian Mysore Sandalwood (Lao Shan Tan)",
    nameZh: "印度迈索尔老山檀香",
    category: "wood",
    description: "Pure spiritual incense timber. Rich in natural santalol oil, calming the central nervous system and inviting divine peace.",
    descriptionZh: "天然香料之王。富含高达 90% 天然檀香醇，气味奶香醇厚悠远，安抚烦躁心灵。",
    origin: "Mysore Heritage Reserve",
    image: "/beads/indian-sandalwood.png",
    colors: {
      base: "#a16207",
      highlight: "#fde047",
      shadow: "#713f12",
      patina1y: "#854d0e",
      patina5y: "#633507",
      patina10y: "#452203",
      pattern: "wood-grain",
    },
    chakras: ["crown", "thirdEye", "throat"],
    element: "wood",
    zodiacs: ["Pisces", "Virgo", "Cancer"],
    aromaScore: 5,
    aromaNote: "Creamy, rich sweet milk sandalwood",
    aromaNoteZh: "温润醇厚甜奶香",
    basePrice: 7.0,
  },
  {
    id: "star-moon-bodhi",
    name: "Star and Moon Bodhi Seed (Xing Yue)",
    nameZh: "海南原生态星月菩提",
    category: "wood",
    description: "Sacred Buddhist meditation seeds. Natural pattern resembling stars surrounding the moon, symbolizing infinite wisdom.",
    descriptionZh: "四大名珠之首。众星捧月天然斑点纹理，随盘玩形成古铜色开片，见证修行蜕变。",
    origin: "Hainan Wild Bodhi Grove",
    image: "/beads/star-moon-bodhi.png",
    colors: {
      base: "#e2d9c8",
      highlight: "#ffffff",
      shadow: "#9e917d",
      patina1y: "#cbbba2",
      patina5y: "#a7906d",
      patina10y: "#7c633d",
      pattern: "speckled",
    },
    chakras: ["crown", "thirdEye"],
    element: "earth",
    zodiacs: ["Virgo", "Pisces", "Capricorn"],
    aromaScore: 1,
    basePrice: 2.5,
  },
  {
    id: "white-bodhi",
    name: "White Jade Bodhi Root (Bai Pu Ti)",
    nameZh: "天然白玉菩提根",
    category: "wood",
    description: "Pure plant seed that polishes to look like creamy white jade. Symbolizes innocence, clarity, and unblemished peace.",
    descriptionZh: "贝叶棕植物种子。质感温润如脂，打磨后如羊脂白玉般光洁，辟邪除烦。",
    origin: "Tropical Mountain Preserve",
    image: "/beads/white-bodhi.png",
    colors: {
      base: "#f1ede6",
      highlight: "#ffffff",
      shadow: "#cbd5e1",
      patina1y: "#e2d8c3",
      patina5y: "#c6b18c",
      patina10y: "#94764b",
      pattern: "swirl",
    },
    chakras: ["crown", "heart"],
    element: "metal",
    zodiacs: ["Cancer", "Taurus", "Libra"],
    aromaScore: 1,
    basePrice: 2.2,
  },
  {
    id: "golden-camphor",
    name: "Golden Camphor Burl (Huang Jin Zhang)",
    nameZh: "缅甸黄金樟水波瘿木",
    category: "wood",
    description: "Dynamic shimmering golden burl grain with natural camphor scent, prized for attracting prosperity and fortune.",
    descriptionZh: "天然水波瘤疤纹理闪闪发光，自带清香防虫防潮，寓意富贵吉祥、财运亨通。",
    origin: "Burma Virgin Mountain Forest",
    image: "/beads/golden-camphor.png",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#713f12",
      patina1y: "#a16207",
      patina5y: "#854d0e",
      patina10y: "#633507",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "sacral"],
    element: "earth",
    zodiacs: ["Leo", "Aries", "Taurus"],
    aromaScore: 4,
    aromaNote: "Invigorating camphor essential oil aroma",
    aromaNoteZh: "清醒提神天然樟木香",
    basePrice: 4.2,
  },
  {
    id: "blood-dragon",
    name: "Imperial Blood Dragon Wood (Xue Long Mu)",
    nameZh: "帝王血龙木透光荧光料",
    category: "wood",
    description: "Semi-translucent miraculous timber that glows ruby-red under direct light, known as the King's Shield Wood.",
    descriptionZh: "强光手电下全透如红玛瑙，油脂极其凝脂充盈，在东方被视为尊贵辟邪之圣木。",
    origin: "Indonesian Rainforest Burl",
    image: "/beads/blood-dragon.png",
    colors: {
      base: "#991b1b",
      highlight: "#f87171",
      shadow: "#450a0a",
      patina1y: "#7f1d1d",
      patina5y: "#5c1313",
      patina10y: "#380909",
      pattern: "wood-grain",
    },
    chakras: ["root", "sacral"],
    element: "fire",
    zodiacs: ["Aries", "Scorpio", "Leo"],
    aromaScore: 2,
    basePrice: 3.8,
  },
  {
    id: "boxwood",
    name: "Chinese Boxwood (Huang Yang Mu)",
    nameZh: "湖北小叶黄杨木老料",
    category: "wood",
    description: "Dense, poreless ivory-smooth grain resembling antique elephant ivory. Ages to an exquisite golden caramel tone.",
    descriptionZh: "千年难长黄杨木。细腻无棕眼如象牙雕刻，随时间氧化呈温润老琥珀焦糖色。",
    origin: "Hubei Mountain Heritage Reserve",
    image: "/beads/boxwood.png",
    colors: {
      base: "#eab308",
      highlight: "#fef08a",
      shadow: "#854d0e",
      patina1y: "#ca8a04",
      patina5y: "#a16207",
      patina10y: "#713f12",
      pattern: "wood-grain",
    },
    chakras: ["solar", "heart"],
    element: "earth",
    zodiacs: ["Virgo", "Taurus", "Capricorn"],
    aromaScore: 2,
    basePrice: 3.2,
  },
];

/**
 * 100% CITES-Compliant & Global Customs-Safe Healing Crystals & Gemstones
 */
export const HEALING_CRYSTALS: BeadMaterial[] = [
  {
    id: "natural-turquoise",
    name: "Natural Turquoise (Lv Song Shi)",
    nameZh: "天然原矿高瓷绿松石",
    category: "gem",
    description: "The stone of the Throat Chakra. Inspires truthful expression, clear communication, and emotional serenity.",
    descriptionZh: "原矿高瓷无优化，青天一抹碧玉色。对应喉轮，增强沟通表达与心灵澄净。",
    origin: "Hubei Zhushan Certified Mine",
    image: "/beads/turquoise.png",
    colors: {
      base: "#06b6d4",
      highlight: "#a5f3fc",
      shadow: "#0e7490",
      patina1y: "#0891b2",
      patina5y: "#0e7490",
      patina10y: "#155e75",
      pattern: "speckled",
    },
    chakras: ["throat", "heart"],
    element: "water",
    zodiacs: ["Sagittarius", "Pisces", "Aquarius"],
    aromaScore: 1,
    basePrice: 6.0,
  },
  {
    id: "lapis-lazuli",
    name: "Royal Lapis Lazuli (Qing Jin Shi)",
    nameZh: "阿富汗帝王青金石 (带金星)",
    category: "gem",
    description: "Deep celestial blue with sparkling golden pyrite specks. Awakens the Third Eye for intuition, wisdom, and mental clarity.",
    descriptionZh: "深邃帝王群青点缀天然金色黄铁矿。对应三眼轮与眉心轮，开启灵性智慧与直觉洞察。",
    origin: "Badakhshan Ancient Mine",
    image: "/beads/lapis-lazuli.png",
    colors: {
      base: "#1d4ed8",
      highlight: "#93c5fd",
      shadow: "#1e3a8a",
      patina1y: "#1e40af",
      patina5y: "#1e3a8a",
      patina10y: "#172554",
      pattern: "speckled",
    },
    chakras: ["thirdEye", "throat"],
    element: "water",
    zodiacs: ["Libra", "Sagittarius", "Virgo"],
    aromaScore: 1,
    basePrice: 5.0,
  },
  {
    id: "red-agate",
    name: "Red Agate (Nan Hong Ma Nao)",
    nameZh: "天然保山满肉南红玛瑙",
    category: "gem",
    description: "Vibrant crimson stone of vitality and courage. Activates the Root Chakra to restore physical passion and emotional balance.",
    descriptionZh: "柿子红天然胶质感。对应海底轮，激发充沛生命力、勇气与内在温暖。",
    origin: "Yunnan Baoshan Heritage Mine",
    image: "/beads/nanhong-agate.png",
    colors: {
      base: "#dc2626",
      highlight: "#fca5a5",
      shadow: "#7f1d1d",
      patina1y: "#b91c1c",
      patina5y: "#991b1b",
      patina10y: "#7f1d1d",
      pattern: "swirl",
    },
    chakras: ["root", "sacral"],
    element: "fire",
    zodiacs: ["Aries", "Scorpio", "Leo"],
    aromaScore: 1,
    basePrice: 5.5,
  },
  {
    id: "amethyst",
    name: "Deep Purple Amethyst (Zi Shui Jing)",
    nameZh: "乌拉圭深紫水晶 (开智助眠)",
    category: "gem",
    description: "Translucent royal purple crystal of spiritual serenity. Calms overactive minds and facilitates restful deep sleep.",
    descriptionZh: "晶莹剔透高贵紫罗兰色。对应顶轮，抚平焦虑思绪，助益深度冥想与甜美睡眠。",
    origin: "Uruguay Deep Vault",
    image: "/beads/amethyst.png",
    colors: {
      base: "#7c3aed",
      highlight: "#ddd6fe",
      shadow: "#4c1d95",
      patina1y: "#6d28d9",
      patina5y: "#5b21b6",
      patina10y: "#4c1d95",
      pattern: "swirl",
    },
    chakras: ["crown", "thirdEye"],
    element: "metal",
    zodiacs: ["Aquarius", "Pisces", "Virgo"],
    aromaScore: 1,
    basePrice: 4.8,
  },
  {
    id: "citrine",
    name: "Golden Citrine (Huang Shui Jing)",
    nameZh: "天然巴西黄水晶 (招财财富之石)",
    category: "gem",
    description: "Sunlight crystallized into quartz. Activates the Solar Plexus for unstoppable confidence, abundant prosperity, and joy.",
    descriptionZh: "太阳与丰盛能量结晶。对应胃轮与太阳神经丛，汇聚八方财富与蓬勃自信。",
    origin: "Minas Gerais Brazil",
    image: "/beads/citrine.png",
    colors: {
      base: "#eab308",
      highlight: "#fef08a",
      shadow: "#854d0e",
      patina1y: "#ca8a04",
      patina5y: "#a16207",
      patina10y: "#713f12",
      pattern: "swirl",
    },
    chakras: ["solar", "sacral"],
    element: "earth",
    zodiacs: ["Leo", "Gemini", "Aries"],
    aromaScore: 1,
    basePrice: 5.2,
  },
  {
    id: "rose-quartz",
    name: "Madagascar Rose Quartz (Fen Jing)",
    nameZh: "马达加斯加天然粉晶 (人缘桃花)",
    category: "gem",
    description: "Gentle pink crystal of unconditional love, compassion, and emotional healing. Opens the Heart Chakra to romance and kindness.",
    descriptionZh: "温柔粉润爱与治愈之石。对应心轮，舒缓心神，招引美好人缘与甜蜜正缘。",
    origin: "Madagascar Rose Deposit",
    image: "/beads/rose-quartz.png",
    colors: {
      base: "#f472b6",
      highlight: "#fbcfe8",
      shadow: "#9d174d",
      patina1y: "#db2777",
      patina5y: "#be185d",
      patina10y: "#831843",
      pattern: "swirl",
    },
    chakras: ["heart"],
    element: "fire",
    zodiacs: ["Taurus", "Libra", "Cancer"],
    aromaScore: 1,
    basePrice: 4.5,
  },
  {
    id: "rutilated-quartz",
    name: "Golden Rutilated Quartz (Jin Fa Jing)",
    nameZh: "天然巴西金发晶 / 钛晶",
    category: "gem",
    description: "Contains natural needles of golden rutile. The most powerful crystal for ambition, executive leadership, and bold breakthrough.",
    descriptionZh: "发丝根根分明闪耀金芒。水晶之王，蕴含无可匹敌的开拓魄力与财气磁场。",
    origin: "Bahia Crystal Mine",
    image: "/beads/rutilated-quartz.png",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#713f12",
      patina1y: "#a16207",
      patina5y: "#854d0e",
      patina10y: "#5a3106",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "crown"],
    element: "metal",
    zodiacs: ["Leo", "Capricorn", "Aries"],
    aromaScore: 1,
    basePrice: 7.5,
  },
  {
    id: "strawberry-quartz",
    name: "Strawberry Quartz (Cao Mei Jing)",
    nameZh: "天然草莓晶 (热情与吸引力)",
    category: "gem",
    description: "Speckled with shimmering red lepidocrocite flecks, enhancing personal magnetism, enthusiasm, and joyful vitality.",
    descriptionZh: "点缀草莓籽般的天然矿物微粒，提升个人气场亲和力与热情活力。",
    origin: "Russian Altai Mountains",
    image: "/beads/strawberry-quartz.png",
    colors: {
      base: "#e11d48",
      highlight: "#fda4af",
      shadow: "#881337",
      patina1y: "#be123c",
      patina5y: "#9f1239",
      patina10y: "#700c25",
      pattern: "speckled",
    },
    chakras: ["heart", "sacral"],
    element: "fire",
    zodiacs: ["Cancer", "Libra", "Sagittarius"],
    aromaScore: 1,
    basePrice: 5.0,
  },
  {
    id: "clear-quartz",
    name: "Clear Crystal Quartz (Bai Shui Jing)",
    nameZh: "高透天然白水晶 (净化灵石)",
    category: "gem",
    description: "The master amplifier crystal. Cleanses negative energy, clarifies memory, and harmonizes all seven chakras.",
    descriptionZh: "万晶之母。晶莹澄澈无杂质，净化磁场浊气，提升直觉与专注力。",
    origin: "Himalayan Glacial Vein",
    image: "/beads/clear-quartz.png",
    colors: {
      base: "#cbd5e1",
      highlight: "#ffffff",
      shadow: "#64748b",
      patina1y: "#94a3b8",
      patina5y: "#64748b",
      patina10y: "#334155",
      pattern: "swirl",
    },
    chakras: ["crown"],
    element: "metal",
    zodiacs: ["Aries", "Gemini", "Leo"],
    aromaScore: 1,
    basePrice: 4.0,
  },
  {
    id: "hetian-jade",
    name: "Hetian Nephrite Jade (He Tian Yu)",
    nameZh: "新疆和田羊脂白玉",
    category: "gem",
    description: "The quintessential stone of Eastern virtue. Oily, tactile smoothness that nurtures gentleness, longevity, and purity.",
    descriptionZh: "东方温润君子之玉。细腻如凝脂，滋养平和心性与长寿安康之福。",
    origin: "Xinjiang Kunlun Mountain River",
    image: "/beads/hetian-jade.png",
    colors: {
      base: "#e2e8f0",
      highlight: "#ffffff",
      shadow: "#94a3b8",
      patina1y: "#cbd5e1",
      patina5y: "#94a3b8",
      patina10y: "#64748b",
      pattern: "swirl",
    },
    chakras: ["heart", "crown"],
    element: "metal",
    zodiacs: ["Taurus", "Cancer", "Libra"],
    aromaScore: 1,
    basePrice: 7.5,
  },
  {
    id: "tigers-eye",
    name: "Golden Tiger's Eye (Hu Yan Shi)",
    nameZh: "天然金虎眼石 (猫眼闪光)",
    category: "gem",
    description: "Silky chatoyancy with dynamic golden-brown light rays. Amplifies confidence, wealth magnetism, and willpower.",
    descriptionZh: "天然流动丝绢猫眼光彩。对应太阳轮，汇聚财富磁场、决断力与无畏自信。",
    origin: "Southern Africa Select Gem",
    image: "/beads/tigers-eye.png",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#713f12",
      patina1y: "#a16207",
      patina5y: "#854d0e",
      patina10y: "#713f12",
      pattern: "gold-fiber",
    },
    chakras: ["solar", "root"],
    element: "earth",
    zodiacs: ["Leo", "Capricorn", "Gemini"],
    aromaScore: 1,
    basePrice: 4.0,
  },
  {
    id: "black-obsidian",
    name: "Rainbow Obsidian (Hei Yao Shi)",
    nameZh: "墨西哥彩虹眼黑曜石",
    category: "gem",
    description: "Volcanic glass with subtle iridescent rings. Powerful psychic protection stone that absorbs negative emotional energies.",
    descriptionZh: "火山熔岩天然凝结，逆光泛出神秘彩虹环。最强辟邪排浊与负能量吸收石。",
    origin: "Mexican Volcanic Highlands",
    image: "/beads/black-obsidian.png",
    colors: {
      base: "#18181b",
      highlight: "#52525b",
      shadow: "#09090b",
      patina1y: "#18181b",
      patina5y: "#09090b",
      patina10y: "#000000",
      pattern: "swirl",
    },
    chakras: ["root"],
    element: "water",
    zodiacs: ["Scorpio", "Sagittarius", "Capricorn"],
    aromaScore: 1,
    basePrice: 3.5,
  },
];

/**
 * 100% CITES-Compliant & Global Customs-Safe Silver & Brass Spacers
 */
export const SACRED_SPACERS: BeadMaterial[] = [
  {
    id: "silver-lotus",
    name: "925 Silver Lotus Guru (Lian Hua Fo Tou)",
    nameZh: "925 纯银浮雕莲花佛头三通",
    category: "spacer",
    description: "Handcrafted 925 sterling silver centerpiece symbolizing purity, rebirth, and spiritual awakening.",
    descriptionZh: "手工錾刻 925 纯银莲花三通母珠，象征出淤泥而不染的心灵解脱与觉悟。",
    origin: "Master Silver Smith Guild",
    image: "/beads/silver-lotus.png",
    colors: {
      base: "#e2e8f0",
      highlight: "#ffffff",
      shadow: "#64748b",
      patina1y: "#cbd5e1",
      patina5y: "#94a3b8",
      patina10y: "#475569",
      pattern: "metallic",
    },
    chakras: ["crown", "heart"],
    element: "metal",
    zodiacs: ["Pisces", "Cancer", "Libra"],
    aromaScore: 1,
    basePrice: 12.0,
  },
  {
    id: "pixiu-charm",
    name: "Silver Pixiu Wealth Guardian (Pi Xiu)",
    nameZh: "925 纯银招财纳福小貔貅",
    category: "spacer",
    description: "Mythical Eastern beast renowned for attracting wealth, safeguarding fortune, and dispelling misfortune.",
    descriptionZh: "吞吐四方之财的神兽护佑，驱除霉运、守护财富磁场稳固不散。",
    origin: "Heritage Foundry Craft",
    image: "/beads/pixiu-charm.png",
    colors: {
      base: "#cbd5e1",
      highlight: "#ffffff",
      shadow: "#475569",
      patina1y: "#94a3b8",
      patina5y: "#64748b",
      patina10y: "#334155",
      pattern: "metallic",
    },
    chakras: ["solar", "root"],
    element: "metal",
    zodiacs: ["Leo", "Taurus", "Scorpio"],
    aromaScore: 1,
    basePrice: 14.0,
  },
  {
    id: "om-mantra",
    name: "Tibetan Om Six-Word Spacer (Om Mantra)",
    nameZh: "藏银六字真言转经隔珠",
    category: "spacer",
    description: "Embossed with the sacred Sanskrit syllable Om Mani Padme Hum for constant inner protection and spiritual harmony.",
    descriptionZh: "微雕六字大明咒梵文，每转动一次即是一次持咒祈福，清净身口意。",
    origin: "Tibetan Artisan Collective",
    image: "/beads/om-mantra.png",
    colors: {
      base: "#94a3b8",
      highlight: "#f1f5f9",
      shadow: "#334155",
      patina1y: "#64748b",
      patina5y: "#475569",
      patina10y: "#1e293b",
      pattern: "metallic",
    },
    chakras: ["throat", "thirdEye"],
    element: "metal",
    zodiacs: ["Sagittarius", "Aquarius", "Gemini"],
    aromaScore: 1,
    basePrice: 8.0,
  },
  {
    id: "brass-ring",
    name: "Vintage Brass Spacer Ring (Huang Tong Ge Pian)",
    nameZh: "复古手工打磨黄铜隔片",
    category: "spacer",
    description: "Slim antique brass ring used between beads to protect timber, improve flex, and add warm vintage character.",
    descriptionZh: "手工复古做旧黄铜薄片，保护木质不磨损，增加手串流线韵律感。",
    origin: "Dacheng Handcraft Lab",
    image: "/beads/brass-ring.png",
    colors: {
      base: "#ca8a04",
      highlight: "#fef08a",
      shadow: "#854d0e",
      patina1y: "#a16207",
      patina5y: "#713f12",
      patina10y: "#422006",
      pattern: "metallic",
    },
    chakras: ["solar"],
    element: "metal",
    zodiacs: ["Gemini", "Virgo", "Capricorn"],
    aromaScore: 1,
    basePrice: 1.5,
  },
];

export const ALL_MATERIALS: BeadMaterial[] = [
  ...SACRED_WOODS,
  ...HEALING_CRYSTALS,
  ...SACRED_SPACERS,
];

export function getMaterialById(id: string): BeadMaterial | undefined {
  return ALL_MATERIALS.find((m) => m.id === id);
}
