export type ProductCategory = "mala" | "teapet" | "carving" | "incense" | "amulet";

export interface ReadyProduct {
  id: string;
  name: string;
  nameZh: string;
  category: ProductCategory;
  categoryNameZh: string;
  priceUsd: number;
  originalPriceUsd?: number;
  woodMaterial: string;
  woodMaterialZh: string;
  beadSizeOrDimensions: string;
  beadSizeOrDimensionsZh: string;
  description: string;
  descriptionZh: string;
  origin: string;
  originZh: string;
  image: string;
  accentBadge?: string;
  accentBadgeZh?: string;
  rating: number;
  reviewCount: number;
  stock: number;
}

export const READY_PRODUCTS: ReadyProduct[] = [
  // 1. 镇店之宝与经典成品手串
  {
    id: "master-zitan-stars",
    name: "Imperial Full-Star Small Leaf Red Sandalwood 108 Mala",
    nameZh: "爆满金星小叶紫檀老料 108 颗念珠手串",
    category: "mala",
    categoryNameZh: "现货手串",
    priceUsd: 268.0,
    originalPriceUsd: 350.0,
    woodMaterial: "Wild Aged Zitan (Pterocarpus santalinus)",
    woodMaterialZh: "百年高密陈化小叶紫檀老料 (爆满金星)",
    beadSizeOrDimensions: "8mm x 108 Beads with Silver Lotus Guru",
    beadSizeOrDimensionsZh: "8mm x 108颗 (附925纯银莲花三通)",
    description: "Sinking-grade century-aged red sandalwood densely packed with golden star filaments. Glassy mirror finish that deepens into royal crimson.",
    descriptionZh: "百年老矿老料，油性极足入水秒沉，棕眼细腻布满天然金星，盘玩后呈现如红宝石般的剔透包浆。",
    origin: "Dacheng Imperial Vault Collection",
    originZh: "大城紫檀珍宝馆老料直采",
    image: "/products/zitan-108.svg",
    accentBadge: "Masterpiece",
    accentBadgeZh: "镇店之宝",
    rating: 5.0,
    reviewCount: 48,
    stock: 5,
  },
  {
    id: "master-nanhong-persimmon",
    name: "Grade-A Baoshan Persimmon Red Agate Meditation Bracelet",
    nameZh: "极品保山满肉柿子红南红玛瑙手串",
    category: "mala",
    categoryNameZh: "现货手串",
    priceUsd: 320.0,
    originalPriceUsd: 420.0,
    woodMaterial: "Baoshan Natural Red Agate",
    woodMaterialZh: "云南保山原矿老坑南红 (满肉微透)",
    beadSizeOrDimensions: "10mm x 19 Beads",
    beadSizeOrDimensionsZh: "10mm x 19颗单圈",
    description: "Full-flesh vibrant persimmon red with gelatinous warm luster. Rebalances the Root Chakra with immense vitality and grounding warmth.",
    descriptionZh: "原矿无胶无裂，浓郁温润柿子红胶质感，对应海底轮，带来无尽生机与内在安宁。",
    origin: "Yunnan Baoshan Certified Mine",
    originZh: "云南保山原矿特选",
    image: "/products/nanhong-bracelet.svg",
    accentBadge: "Rare Gem",
    accentBadgeZh: "极品原矿",
    rating: 4.9,
    reviewCount: 36,
    stock: 3,
  },
  {
    id: "master-chenxiang-sinking",
    name: "Wild Sinking Agarwood (Chen Xiang) Meditation Beads",
    nameZh: "印尼野生加里曼丹沉水老料沉香手串",
    category: "mala",
    categoryNameZh: "现货手串",
    priceUsd: 158.0,
    originalPriceUsd: 198.0,
    woodMaterial: "Wild Kalimantan Agarwood",
    woodMaterialZh: "加里曼丹野生九分沉香老料",
    beadSizeOrDimensions: "12mm x 16 Beads",
    beadSizeOrDimensionsZh: "12mm x 16颗 (沉水级)",
    description: "Rich in natural resin veins. Emanates cool, sweet herbal medicinal aroma that calms the central nervous system instantly.",
    descriptionZh: "油脂饱满成丝，常温散发清甜花凉香气，安魂定魄，是修心冥想的顶级香木圣品。",
    origin: "Wild Forest Certified Resin Stock",
    originZh: "野生老料原木直切",
    image: "/products/chenxiang-mala.svg",
    accentBadge: "Aromatherapy",
    accentBadgeZh: "天然香圣",
    rating: 5.0,
    reviewCount: 62,
    stock: 8,
  },
  {
    id: "turquoise-raw-beads",
    name: "High-Porcelain Hubei Zhushan Raw Turquoise & Gold Phoebe Mala",
    nameZh: "原矿高瓷蓝绿松石单圈配金丝楠手串",
    category: "mala",
    categoryNameZh: "现货手串",
    priceUsd: 188.0,
    originalPriceUsd: 240.0,
    woodMaterial: "High-Porcelain Turquoise & Gold Phoebe",
    woodMaterialZh: "湖北十堰竹山原矿高瓷松石 + 四川金丝楠",
    beadSizeOrDimensions: "10mm x 18 Beads",
    beadSizeOrDimensionsZh: "10mm x 18颗",
    description: "Vibrant robin-egg blue stone interlaced with delicate golden-brown spiderweb matrix. Opens the Throat Chakra for truthful clarity.",
    descriptionZh: "原矿无优化高瓷天空蓝，天然铁线纹理独特，搭配金丝楠水波纹，澄澈心灵。",
    origin: "Zhushan Heritage Mine",
    originZh: "竹山绿松石原矿",
    image: "/products/turquoise-phoebe.svg",
    accentBadge: "Top Seller",
    accentBadgeZh: "人气雅赏",
    rating: 4.95,
    reviewCount: 79,
    stock: 12,
  },

  // 2. 红木雕刻小件与案头茶宠 (Tea Pets & Desk Figurines)
  {
    id: "carving-sandalwood-dragon",
    name: "Hand-Carved Green Sandalwood Azure Dragon Tea Pet",
    nameZh: "纯手工雕刻野生绿檀木【祥龙戏珠】案头茶宠摆件",
    category: "teapet",
    categoryNameZh: "案头茶宠",
    priceUsd: 88.0,
    originalPriceUsd: 128.0,
    woodMaterial: "Wild Green Sandalwood (Verawood)",
    woodMaterialZh: "整木纯手工立体圆雕野生绿檀",
    beadSizeOrDimensions: "11.5cm x 6.5cm x 5.8cm (220g)",
    beadSizeOrDimensionsZh: "长11.5cm x 宽6.5cm x 高5.8cm (约220克)",
    description: "Intricately carved single-block sacred sandalwood dragon. Daily tea nourishment transforms it into a translucent jade green finish with sweet aroma.",
    descriptionZh: "大师纯手工立体微雕，龙鳞毕现，霸气生动。经茶水日常温养，木色渐呈碧玉翡翠色，香气愈发浓郁。",
    origin: "Dacheng Master Carver Guild",
    originZh: "大城工艺大师工坊出品",
    image: "/products/dragon-teapet.svg",
    accentBadge: "Hand Carved",
    accentBadgeZh: "大师手雕",
    rating: 5.0,
    reviewCount: 31,
    stock: 6,
  },
  {
    id: "carving-ebony-pixiu",
    name: "Solid Dense Ebony Pixiu Wealth Guardian Desk Figurine",
    nameZh: "高密沉水黑檀【招财霸王貔貅】桌面镇宅把件",
    category: "carving",
    categoryNameZh: "红木把件",
    priceUsd: 75.0,
    originalPriceUsd: 98.0,
    woodMaterial: "High-Density Sinking Black Ebony",
    woodMaterialZh: "百年沉水黑檀老料 (高密无裂)",
    beadSizeOrDimensions: "9.8cm x 5.2cm x 4.6cm (195g)",
    beadSizeOrDimensionsZh: "长9.8cm x 宽5.2cm x 高4.6cm",
    description: "Sinking-dense ebony carved mythical beast. Shields home & workspace from negative energies and anchors stable financial magnetism.",
    descriptionZh: "整木雕琢，通体沉黑乌亮，双目有神，口衔金钱，是书房案头守财纳福的祥瑞重器。",
    origin: "Dacheng Heritage Carving Lab",
    originZh: "大城京作雕刻工坊",
    image: "/products/ebony-pixiu.svg",
    accentBadge: "Wealth Amulet",
    accentBadgeZh: "招财辟邪",
    rating: 4.9,
    reviewCount: 42,
    stock: 9,
  },
  {
    id: "carving-gold-phoebe-lotus",
    name: "Gold Phoebe Zen Lotus Flower Handcrafted Incense Burner",
    nameZh: "四川金丝楠【禅意并蒂莲】手工雕刻线香插/承香盘",
    category: "incense",
    categoryNameZh: "香道雅器",
    priceUsd: 65.0,
    originalPriceUsd: 85.0,
    woodMaterial: "Century Gold Phoebe (Jin Si Nan)",
    woodMaterialZh: "四川老料金丝楠 (天然水波荧光)",
    beadSizeOrDimensions: "13.0cm x 7.5cm x 3.2cm",
    beadSizeOrDimensionsZh: "长13cm x 宽7.5cm (含黄铜香孔)",
    description: "Delicately carved lotus petal dish with natural golden chatoyant waves. Holds incense sticks safely while creating a tranquil Zen space.",
    descriptionZh: "花瓣层叠如生，天然水波金丝流动。置于茶席琴室，焚香静气，顿生超然物外之感。",
    origin: "Ancient Root Timber Collective",
    originZh: "大城香道工坊",
    image: "/products/lotus-incense.svg",
    accentBadge: "Zen Decor",
    accentBadgeZh: "茶室雅器",
    rating: 4.85,
    reviewCount: 27,
    stock: 14,
  },
  {
    id: "carving-cypress-fidget",
    name: "Taihang Cliff Cypress Meditation Worry Bead Hand Roller",
    nameZh: "太行崖柏雀眼【随身解压掌心把件 / 盘玩手捻】",
    category: "carving",
    categoryNameZh: "红木把件",
    priceUsd: 48.0,
    originalPriceUsd: 68.0,
    woodMaterial: "Taihang Cliff Cypress (Bird-Eye Grade)",
    woodMaterialZh: "太行悬崖陈化舍利崖柏 (满雀眼虎皮纹)",
    beadSizeOrDimensions: "6.8cm x 3.8cm (Ergonomic Fit)",
    beadSizeOrDimensionsZh: "长6.8cm x 径3.8cm (掌心贴合)",
    description: "Smooth tactile handheld object for anxiety relief, fidgeting, and mantra counting. Releases intense natural herbal cedar aroma as you roll it.",
    descriptionZh: "符合人体工学的掌心弧度，指尖反复盘捻可刺激手部经络、舒缓工作焦虑，天然柏木香气提神醒脑。",
    origin: "Taihang Mountain Harvest",
    originZh: "太行山绝壁陈化料",
    image: "/products/cypress-roller.svg",
    accentBadge: "Stress Relief",
    accentBadgeZh: "解压神器",
    rating: 4.95,
    reviewCount: 88,
    stock: 18,
  },
  {
    id: "amulet-peachwood-pendant",
    name: "Sacred Mount Tai Lightning Peach Wood Protection Amulet",
    nameZh: "泰山雷击桃木【太上老君 · 乾坤护身牌】随身车挂/项链",
    category: "amulet",
    categoryNameZh: "护身挂件",
    priceUsd: 38.0,
    originalPriceUsd: 52.0,
    woodMaterial: "Sacred Lightning-Struck Peach Wood",
    woodMaterialZh: "正宗泰山雷击桃木老料 (手工精雕)",
    beadSizeOrDimensions: "6.0cm x 4.0cm x 1.0cm (with silk cord)",
    beadSizeOrDimensionsZh: "长6cm x 宽4cm (配手工编织朱砂绳)",
    description: "The ancient Daoist talisman wood for absolute psychic protection and dispelling negative energy during travel and sleep.",
    descriptionZh: "东方道家经典避煞护身符，纯手工双面精微雕刻，可佩戴于胸前或悬挂于车内，护佑一路出入平安。",
    origin: "Mount Tai Heritage Grove",
    originZh: "泰山古桃木精选",
    image: "/products/peach-amulet.svg",
    accentBadge: "Protection",
    accentBadgeZh: "出入平安",
    rating: 5.0,
    reviewCount: 54,
    stock: 25,
  },
];

export function getProductById(id: string): ReadyProduct | undefined {
  return READY_PRODUCTS.find((p) => p.id === id);
}
